services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-stg
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    hostname: minio-stg
    command: server /data --console-address ":9001"
    volumes:
      - minio-stg:/data
    networks:
      - airflow-project

volumes:
  minio-stg:

networks:
  airflow-project:
    external: true